### ISSUE TITLE
enable http2

### ISSUE THREAD

**Issue by ahansson89** [million12/docker-nginx-php#10]

**Comment by ryzy** [comment]
Hi Alexander. Support for HTTP/2 has been done in parent million12/nginx image https://github.com/million12/docker-nginx. The default vhost in this repo has been updated accordingly, so I consider it done ;)

**Comment by ahansson89** [comment]
Awesome, thanks! I decided to use a multi container solution for this project and went with the official nginx image and hhvm over fastcgi. I will have this in mind for any future projects.
