### ISSUE TITLE
do not allocate TTY?

### ISSUE THREAD

**Issue by basvdheijden** [million12/docker-nginx-php#12]
I've got a little problem with this image.

It's quite weird, but if I run `docker-compose run web ls` from within my VPS, it all works out fine.
However, if I try to run it over SSH, like so: `ssh myvps docker-compose run web ls` it very annoyingly always attached to the tty, so my process never exits. Also, if I CTRL+C, the container keeps hanging around if I do `docker-compose ps` as `docker_run_web_XX`...

Do you have any idea how to mitigate this problem?

**Comment by pozgo** [comment]
You could use `docker-compose up -d` that will demonize the container
