### ISSUE TITLE
Add ngx_pagespeed module and daemon

### ISSUE THREAD

**Issue by kyvaith** [million12/docker-nginx-php#13]
Hi,

Could you add ngx_pagespeed module and daemon to your image? It's excellent add-on for WordPress-like web apps. Also please check optimizations done in Centmin Mod, maybe you could cherrypick something from there: http://centminmod.com/

**Comment by yudianguo** [comment]
ok

**Comment by kyvaith** [comment]
@yudianguo are you a contributor to this repository?

**Comment by yudianguo** [comment]
sorry, i see the wrong.just watch this project.

**Comment by ryzy** [comment]
Hi,

I'm not convinced about adding this module to this image. Couple of reasons:
- That module tries to tackle issues which should/could be resolved by website developer and does it in some semi-magical way. It might produce unexpected results, not always desired.
- I have an impression that after initial excitement the development of that module slows down which suggest that people figure out it's not the best way to speed up their website.

I'd suggest you create an image, based on this one, tailored for your project, with that module installed / configured as needed.

**Comment by kyvaith** [comment]
Marcin, thanks for reply. I know about all this uncertainty about ngx_pagespeed, but personally I'm impressed with the efficiency and compatibility with WordPress. In the end I decided to make my own puppet/docker stack with this module and other improvements. Version 0.1 is here: https://github.com/kyvaith/Adaptive-Cloud/tree/beta-0.1
Regards,
Tom.
