### ISSUE TITLE
A few questions regarding customization of this container

### ISSUE THREAD

**Issue by reypm** [million12/docker-nginx-php#15]
So, I've been reading carefully each file under `container-files` directory because I want to add `xdebug` extension and also install some composer packages by default and under global but I've a few questions regarding this:
- Add `xdebug` would be easy as add `php70-php-pecl-xdebug` extension but, where I should add the default configuration for `xdebug` to work properly? I mean the configuration that install by default under `/etc/php.d/15-xdebug.ini` file on Fedora/CentOS. 
  - How do I expose the port `9001` so I can use it from within the IDE? The port should be listening for incoming connection from the host.
  - How do I install some composer packages globally like PHP Code Sniffer, PHP Mess Detector and so on?
  - I've seen that composer is already included on the container, is installed globally?

That's it. Can any one help me to achieve this?

**Comment by ryzy** [comment]
@reypm,
- you're right about xdebug - just install the mentioned package
- re 9001 port: if you have running daemon inside the container, just expose it outside (-p option or ports: in docker-compose)
- re composer: yes, it's installed globally (so you should be able to call it inside your Dockerfile)

Good luck! :)

**Comment by ryzy** [comment]
Ah, and you can add PHP config files in /etc/php.d in your container (beware of the order - I intentionally prefixed some of them with `zzz` so they are read last (see https://github.com/million12/docker-nginx-php/tree/master/container-files/etc/php.d )

**Comment by reypm** [comment]
@ryzy 
- re 9001 port: can this be exposed by default to avoud the `-p` option all the time or I just need to append the `-p` option one time when container run for first time? My doubt is I have to add it each time the container is up.

I am not following you on the latest comment about the order? I prefixed with `15` because this is how is installed by default, could be any problem if I leave it around as it's by default?

**Comment by ryzy** [comment]
Just build the image and see if your configuration is applied there ;)

If you add your file _after_ you installed xdebug, yes, then it will work ;)

**Comment by reypm** [comment]
@ryzy thanks, I'll keep learning, closing this

**Comment by reypm** [comment]
@ryzy how do you handle the tags? I mean how do you know when to install php 55 or php 56 or php 70? I need to know where the sources are coming from in order to install xdebug properly on each of them, any clue? 

I am creating my own image extending from yours as: 

```
FROM million12/nginx-php:php55
```

Then after I should install Xdebug and setup it properly but I am missing what I've asked before

**Comment by ryzy** [comment]
Hi again ;-)

What do you mean by `how do you know when to install php 55 or php 56 or php 70`?

I decide based on my application requirements... if it can run on PHP 7.0, I install it. If I have something older, I user older version.

**Comment by reypm** [comment]
@ryzy nvm. I didn't read so good before and now when I was looking the answer for your question I found also the answer for mine. I was trying to find the `Dockerfile` when you or any decide to install PHP55 using `million12/nginx-php:php55` the key is on the docs: "For different PHP versions, look up different **branches** of this repository." I wasn't looking for branches but for repositories and that was my error. 

Thanks anyway
