### ISSUE TITLE
Mapped volumes, where did they go under the host?

### ISSUE THREAD

**Issue by reypm** [million12/docker-nginx-php#16]
I've seen this on docs:

```
/data/www # meant to contain web content
/data/www/default # root directory for the default vhost
/data/logs/ # Nginx, PHP logs
/data/tmp/php/ # PHP temp directories
```

My question is, where this directories are mapped on the host?

**Comment by ryzy** [comment]
Hi Reynier,

They are not mapped on the host ;) You have to map it explicitly when you create the volume (e.g. with docker-compose v2) or start a container (-v option).

If you didn't work much with volumes/storage, I suggest you read https://docs.docker.com/engine/tutorials/dockervolumes/

**Comment by reypm** [comment]
Thanks @ryzy I think the way to go here is a data volume container. However I did read the doc but isn't clear to me since I am kind of new with Docker (had been working forever with VM). Let's said that I want to copy|share from host to volume as soon as container start the content from `/home/reypm/www` I think this should be mapped to `/data/www` or `/data/www/default` in the container not sure which one is the right since both seems to be the same, one for default the other for any other vhost that I could add in the future.

Well this is the theory but what I don't know is how to properly build the `compose.yml` file for achieve this, could you give me a little push?

**Comment by ryzy** [comment]
Don't use data container, it's an old approach and not recommended anymore. Read about `docker volume`.

For en example... have a look at https://github.com/million12/neos-protobrew-distribution/blob/master/docker-compose.yml - that `web` container `million12/neos-protobrew-distribution` actually is built on top of `million12/docker-nginx-php` so you might find some inspirations there. It also uses that new approach with docker volumes.

**Comment by reypm** [comment]
@ryzy thanks, I'll keep learning, closing this

**Comment by reypm** [comment]
@ryzy I have a question for you. From the file you leave me as an example:

```
volumes:
  dbdata:
  webdata:
services:
  db:
    volumes:
      - dbdata:/var/lib/mysql
```

I am seeing `/var/lib/mysql` mapped to `dbdata` and this latest leave under `volumes` definition, but what this mean? I mean where this is attached to the host so I can place my code or config files there and/or persist data when container are stopped?
