### ISSUE TITLE
Understanding the Dockerfile of this project

### ISSUE THREAD

**Issue by reypm** [million12/docker-nginx-php#17]
I am studying carefully the `Dockerfile` from this project since I need to build something similar but based on Ubuntu and less complex. I have a few questions regarding it and I hope @ryzy can help me :)

I can see [zz-php-directories.ini](https://github.com/million12/docker-nginx-php/blob/master/container-files/etc/php.d/zz-php-directories.ini) and [zz-php.ini](https://github.com/million12/docker-nginx-php/blob/master/container-files/etc/php.d/zz-php.ini) in `container-files` directory, I guess those are some PHP configurations that gets override, so my first question is: where? I mean where in the `Dockerfile` or maybe in a `.sh` script did you override them?

Maybe I am complete lost and this is something basic from Docker but I am still learning

**Comment by ryzy** [comment]
They are added here: https://github.com/million12/docker-nginx-php/blob/master/Dockerfile#L113 (line with `ADD container-files /`). With that, the mentioned files will end up in `etc/php.d` and thus contribute to PHP configuration.

**Comment by reypm** [comment]
@ryzy I have the following in my Dockerfile:

```
COPY /container-files/etc/php.d/zz-php.ini /etc/php5/mods-available/zz-php.ini
COPY /container-files/etc/php.d/zz-php-directories.ini /etc/php5/mods-available/zz-php-directories.ini
```

if I am following you, that could be translated on:

```
ADD /container-files
```

And the files will be copied on the same path specified but in the container, right?

**Comment by ryzy** [comment]
The syntax is `ADD [what] [where]`

So `ADD container-files /` is translated to copying `container-files` dir (relative to Dockerfile, so probably NOT `/container-files` as you wrote) into `/` location inside the image (note the space before `/` in the instruction).

And to answer your question: yes, you can simplify it to that, assuming the directory structure inside your `container-files` is the one expected inside the image.

**Comment by reypm** [comment]
Great, thanks
