### ISSUE TITLE
Starting my own repository based on yours or fork this and add my contribution to a new branch?

### ISSUE THREAD

**Issue by reypm** [million12/docker-nginx-php#19]
Hi there, I have recently decide to start my own repository based on yours since it's an excellent job, why?because yours has several things that I wont use and will make the image larger (like Node, Ruby or NMP packages). Also I want to add my own libraries as Xdebug so I have open [this question](http://stackoverflow.com/questions/40657259/which-is-the-right-way-to-duplicate-a-repository-and-get-rid-of-any-dependency-w) in StackOverflow and I would like to know your opinion before keep going.

I don't know if that's the right way or choice or you have a better idea but I am open to heard about them.

Thx in advance

**Comment by pozgo** [comment]
I think best would be making a fork. This image is heave sue to lots of additional packahges being installed and compatibility issues with different software (like Neos) 

I'm closing this.
